### ISSUE TITLE
Transparent walls

### ISSUE THREAD

**Issue by dhhdhshdja** [GreatCorn/MASMZE-3D#1]
When I am playing game I am having this graphical issue
![image](https://github.com/user-attachments/assets/42cf7984-6862-479c-a3d6-3ea061f7f4d7)
![image](https://github.com/user-attachments/assets/191d5bc2-89ab-49cb-b8d0-9b4d8476337c)
![image](https://github.com/user-attachments/assets/9c484b90-0003-43f5-9f02-f512b48faf0c)
![image](https://github.com/user-attachments/assets/6ffb7102-923b-476c-b703-bff1fbe4edb6)
![image](https://github.com/user-attachments/assets/98c8604f-68f0-4c75-8377-92e50db2ea86)

**Comment by GreatCorn** [comment]
Looks like a graphical driver problem. Can you please specify your OS/compatibility layer and graphics card?

**Comment by dhhdhshdja** [comment]
OS: Debian 12
CL: Wine 8.0

**Comment by GreatCorn** [comment]
> OS: Debian 12 CL: Wine 8.0

Tested with Wine 9.0, couldn't replicate. Try updating Wine and check if your Mesa drivers are up to date

**Comment by dhhdhshdja** [comment]
> > OS: Debian 12 CL: Wine 8.0
> 
> Tested with Wine 9.0, couldn't replicate. Try updating Wine and check if your Mesa drivers are up to date

Updating Wine to 9.0 and mesa is not possible on Debian because of old libraries. Tested on Fedora 40 with Wine 9.0 and Wayland. Works well, closing issue.
